import asyncio
import inspect
from datetime import datetime
from typing import Any, Dict, List

from app.models.workflow_model import AgentStep
from app.tools.all_tools import TOOL_MAP
from app.utils.logger import get_logger

logger = get_logger(__name__)


def _adapt_parameters(tool_name: str, action: str, params: Dict[str, Any], method) -> Dict[str, Any]:
    """
    Adapter layer: reconciles planner-generated parameters with actual tool
    method signatures so mismatched keys never reach the tool as a TypeError.

    Strategy:
      1. If all required params are already present → pass through unchanged.
      2. Otherwise, inspect the method signature and attempt to remap common
         aliases (e.g. planner sends `task`, tool expects `query`).
      3. Fill any still-missing required params with safe sentinel defaults
         and log a warning so the mismatch is visible in logs.
    """
    sig = inspect.signature(method)
    sig_params = sig.parameters  # OrderedDict of param_name → Parameter

    # Determine which params are required (no default value)
    required = {
        name
        for name, p in sig_params.items()
        if name != "self" and p.default is inspect.Parameter.empty
    }

    # If everything required is already supplied, nothing to do
    if required.issubset(params.keys()):
        return params

    adapted = dict(params)  # copy so we don't mutate original

    # ── Common alias remapping ────────────────────────────────────────────
    ALIASES = {
        # planner key  →  tool key
        "task":         ["query", "title", "job_title", "order_id",
                         "transaction_id", "report_type"],
        "input":        ["query", "message"],
        "text":         ["query", "message", "body"],
        "subject":      ["title"],
    }

    for planner_key, candidates in ALIASES.items():
        if planner_key in adapted:
            for tool_key in candidates:
                if tool_key in sig_params and tool_key not in adapted:
                    adapted[tool_key] = adapted.pop(planner_key)
                    logger.warning(
                        f"[Adapter] '{tool_name}.{action}': remapped "
                        f"'{planner_key}' → '{tool_key}'"
                    )
                    break

    # ── Fill still-missing required params with safe defaults ─────────────
    SAFE_DEFAULTS = {
        "query":          "general query",
        "transaction_id": "TXN-UNKNOWN",
        "order_id":       "ORD-UNKNOWN",
        "job_title":      "Software Engineer",
        "report_type":    "operations",
        "title":          "Auto-generated ticket",
        "description":    "Auto-generated by AutoOps AI",
        "team":           "ops",
        "message":        "Task completed",
        "to":             "team@company.com",
        "subject":        "AutoOps Notification",
        "body":           "Task completed",
        "channel":        "general",
        "table":          "orders",
        "record_id":      "REC-UNKNOWN",
        "data":           {},
        "invoice_id":     "INV-UNKNOWN",
        "email":          "team@company.com",
        "ticket_id":      "OPS-UNKNOWN",
        "status":         "open",
        "amount":         0.0,
        "customer_id":    "CUST-UNKNOWN",
        "problem":        "unknown problem",
        "solution":       "no solution provided",
        "issue":          "unspecified issue",
    }

    still_missing = required - adapted.keys()
    for key in still_missing:
        default = SAFE_DEFAULTS.get(key, "unknown")
        adapted[key] = default
        logger.warning(
            f"[Adapter] '{tool_name}.{action}': missing required param "
            f"'{key}' — using default: {repr(default)}"
        )

    # Drop keys that the method doesn't accept (unless it has **kwargs)
    has_var_keyword = any(
        p.kind == inspect.Parameter.VAR_KEYWORD
        for p in sig_params.values()
    )
    if not has_var_keyword:
        extra = [k for k in list(adapted) if k not in sig_params]
        for k in extra:
            logger.warning(
                f"[Adapter] '{tool_name}.{action}': dropping unexpected param '{k}'"
            )
            del adapted[k]

    return adapted


class ExecutorAgent:
    def __init__(self):
        self._instances: Dict[str, Any] = {}

    def _get_tool(self, tool_name: str):
        if tool_name not in self._instances:
            cls = TOOL_MAP.get(tool_name)
            if not cls:
                raise ValueError(
                    f"Unknown tool: '{tool_name}'. Available: {list(TOOL_MAP.keys())}"
                )
            self._instances[tool_name] = cls()
        return self._instances[tool_name]

    async def execute_step(self, step: AgentStep) -> AgentStep:
        step.started_at = datetime.utcnow()
        step.status = "running"
        logger.info(
            f"[ExecutorAgent] Step {step.step_number}: {step.action} via {step.tool}"
        )

        try:
            tool = self._get_tool(step.tool)
            method = getattr(tool, step.action, None)

            # Fall back to execute() if specific method not found
            if method is None:
                logger.warning(
                    f"Method '{step.action}' not found on {step.tool}, using execute()"
                )
                method = getattr(tool, "execute", None)
                if method is None:
                    raise AttributeError(
                        f"Tool '{step.tool}' has no method '{step.action}' or 'execute'"
                    )

            params = step.input_data.get("parameters", {})

            # Reconcile planner params with actual tool signature
            params = _adapt_parameters(step.tool, step.action, params, method)

            if asyncio.iscoroutinefunction(method):
                result = await method(**params)
            else:
                result = await asyncio.to_thread(method, **params)

            step.output_data = (
                result if isinstance(result, dict) else {"result": str(result)}
            )
            step.status = "completed"
            logger.info(f"[ExecutorAgent] Step {step.step_number} ✓ completed")

        except Exception as e:
            step.status = "failed"
            step.error = str(e)
            logger.error(
                f"[ExecutorAgent] Step {step.step_number} ✗ failed: {e}"
            )

        finally:
            step.completed_at = datetime.utcnow()

        return step

    async def execute_plan(self, plan: Dict[str, Any]) -> List[AgentStep]:
        steps_config = plan.get("steps", [])
        results: List[AgentStep] = []

        for cfg in steps_config:
            step = AgentStep(
                step_number=cfg.get("step_number", len(results) + 1),
                agent=cfg.get("agent", "executor"),
                tool=cfg.get("tool", ""),
                action=cfg.get("action", "execute"),
                input_data={"parameters": cfg.get("parameters", {})},
            )

            await asyncio.sleep(0.3)
            step = await self.execute_step(step)
            results.append(step)

            # Stop on critical failure (risk=high)
            if step.status == "failed" and plan.get("risk_level") == "high":
                logger.warning(
                    "[ExecutorAgent] High-risk step failed — halting execution"
                )
                break

        return results